# Generated by Django 2.1.1 on 2018-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDIAccount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('ipHost', models.CharField(max_length=250)),
                ('userName', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('input_path', models.CharField(max_length=1000)),
                ('output_path', models.CharField(max_length=1000)),
                ('ip_hostOut', models.CharField(max_length=250)),
                ('user_nameOut', models.CharField(max_length=1000)),
                ('passwordOut', models.CharField(max_length=1000)),
            ],
        ),
    ]
