# Generated by Django 2.1.1 on 2018-10-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ediaccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediaccount',
            name='email',
        ),
    ]
